
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL,
    // Falls back to DATABASE_URL locally (single non-pooled Postgres).
    // Set DIRECT_URL explicitly against Neon so migrations bypass the pooler.
    directUrl: process.env.DIRECT_URL || process.env.DATABASE_URL,
  },
});
